// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS.Template.API.Entities;

namespace PS.Template.AccessData.Migrations
{
    [DbContext(typeof(SucursalDBContext))]
    [Migration("20201113101805_CreateSucursalDB")]
    partial class CreateSucursalDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PS.Template.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idDireccion")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdLocalidad")
                        .HasColumnName("idLocalidad")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<double>("Longitud")
                        .HasColumnType("float")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Direccion");

                    b.HasData(
                        new
                        {
                            IdDireccion = 1,
                            Altura = 408,
                            Calle = "Av. del Libertador",
                            IdLocalidad = 1,
                            Latitud = -34.590174300000001,
                            Longitud = -58.379654500000001
                        },
                        new
                        {
                            IdDireccion = 2,
                            Altura = 1201,
                            Calle = "Av. Belgrano",
                            IdLocalidad = 2,
                            Latitud = -34.613230000000001,
                            Longitud = -58.383805000000002
                        },
                        new
                        {
                            IdDireccion = 3,
                            Altura = 1999,
                            Calle = "Av. Gral. José de San Martín",
                            IdLocalidad = 3,
                            Latitud = -34.796816999999997,
                            Longitud = -58.279026999999999
                        },
                        new
                        {
                            IdDireccion = 4,
                            Altura = 204,
                            Calle = "3 de Febrero",
                            IdLocalidad = 4,
                            Latitud = -34.725701000000001,
                            Longitud = -58.262264999999999
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.EstadoSucursal", b =>
                {
                    b.Property<int>("IdEstado")
                        .HasColumnName("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdEstado");

                    b.ToTable("EstadoSucursal");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            Descripcion = "Habilitada"
                        },
                        new
                        {
                            IdEstado = 2,
                            Descripcion = "Inhabilitada"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idLocalidad")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cp")
                        .HasColumnName("CP")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnName("idProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Localidad");

                    b.HasData(
                        new
                        {
                            IdLocalidad = 1,
                            Cp = 1001,
                            IdProvincia = 1,
                            Nombre = "Retiro"
                        },
                        new
                        {
                            IdLocalidad = 2,
                            Cp = 1002,
                            IdProvincia = 1,
                            Nombre = "Monserrat"
                        },
                        new
                        {
                            IdLocalidad = 3,
                            Cp = 1888,
                            IdProvincia = 1,
                            Nombre = "Florencio Varela"
                        },
                        new
                        {
                            IdLocalidad = 4,
                            Cp = 1878,
                            IdProvincia = 1,
                            Nombre = "Quilmes"
                        },
                        new
                        {
                            IdLocalidad = 5,
                            Cp = 1870,
                            IdProvincia = 1,
                            Nombre = "Avellaneda"
                        },
                        new
                        {
                            IdLocalidad = 6,
                            Cp = 1884,
                            IdProvincia = 1,
                            Nombre = "Berazategui"
                        },
                        new
                        {
                            IdLocalidad = 7,
                            Cp = 1824,
                            IdProvincia = 1,
                            Nombre = "Lanus"
                        },
                        new
                        {
                            IdLocalidad = 8,
                            Cp = 1828,
                            IdProvincia = 1,
                            Nombre = "Banfield"
                        },
                        new
                        {
                            IdLocalidad = 9,
                            Cp = 1900,
                            IdProvincia = 1,
                            Nombre = "La Plata"
                        },
                        new
                        {
                            IdLocalidad = 10,
                            Cp = 1886,
                            IdProvincia = 1,
                            Nombre = "Ranelagh"
                        },
                        new
                        {
                            IdLocalidad = 11,
                            Cp = 1846,
                            IdProvincia = 1,
                            Nombre = "San Francisco Solano"
                        },
                        new
                        {
                            IdLocalidad = 12,
                            Cp = 1923,
                            IdProvincia = 1,
                            Nombre = "Berisso"
                        },
                        new
                        {
                            IdLocalidad = 13,
                            Cp = 1875,
                            IdProvincia = 1,
                            Nombre = "Wilde"
                        },
                        new
                        {
                            IdLocalidad = 14,
                            Cp = 7130,
                            IdProvincia = 1,
                            Nombre = "Chascomus"
                        },
                        new
                        {
                            IdLocalidad = 15,
                            Cp = 1931,
                            IdProvincia = 1,
                            Nombre = "Punta Lara"
                        },
                        new
                        {
                            IdLocalidad = 16,
                            Cp = 1885,
                            IdProvincia = 1,
                            Nombre = "Guillermo Hudson"
                        },
                        new
                        {
                            IdLocalidad = 17,
                            Cp = 1876,
                            IdProvincia = 1,
                            Nombre = "Bernal"
                        },
                        new
                        {
                            IdLocalidad = 18,
                            Cp = 1018,
                            IdProvincia = 1,
                            Nombre = "Recoleta"
                        },
                        new
                        {
                            IdLocalidad = 19,
                            Cp = 1917,
                            IdProvincia = 1,
                            Nombre = "Punta Indio"
                        },
                        new
                        {
                            IdLocalidad = 20,
                            Cp = 1874,
                            IdProvincia = 1,
                            Nombre = "Temperley"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idProvincia")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincia");

                    b.HasData(
                        new
                        {
                            IdProvincia = 1,
                            Nombre = "Buenos Aires"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idSucursal")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDireccion")
                        .HasColumnName("idDireccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnName("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstado");

                    b.ToTable("Sucursal");

                    b.HasData(
                        new
                        {
                            IdSucursal = 1,
                            IdDireccion = 1,
                            IdEstado = 1,
                            Nombre = "EnvioYa Retiro"
                        },
                        new
                        {
                            IdSucursal = 2,
                            IdDireccion = 2,
                            IdEstado = 1,
                            Nombre = "EnvioYa Monserrat"
                        },
                        new
                        {
                            IdSucursal = 3,
                            IdDireccion = 3,
                            IdEstado = 1,
                            Nombre = "EnvioYa Florencio Varela"
                        },
                        new
                        {
                            IdSucursal = 4,
                            IdDireccion = 4,
                            IdEstado = 1,
                            Nombre = "EnvioYa Quilmes"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Localidad", "IdLocalidadNavigation")
                        .WithMany("Direccion")
                        .HasForeignKey("IdLocalidad")
                        .HasConstraintName("FK_Direccion_Localidad")
                        .IsRequired();
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Localidad", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Provincia", "IdProvinciaNavigation")
                        .WithMany("Localidad")
                        .HasForeignKey("IdProvincia")
                        .HasConstraintName("FK_Localidad_Provincia")
                        .IsRequired();
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Direccion", "IdDireccionNavigation")
                        .WithMany("Sucursal")
                        .HasForeignKey("IdDireccion")
                        .HasConstraintName("FK_Sucursal_Direccion")
                        .IsRequired();

                    b.HasOne("PS.Template.Domain.Entities.EstadoSucursal", "IdEstadoNavigation")
                        .WithMany("Sucursal")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Sucursal_EstadoSucursal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
