// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PS.Template.API.Entities;

namespace PS.Template.AccessData.Migrations
{
    [DbContext(typeof(SucursalDBContext))]
    partial class SucursalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PS.Template.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idDireccion")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("IdLocalidad")
                        .HasColumnName("idLocalidad")
                        .HasColumnType("int");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.EstadoSucursal", b =>
                {
                    b.Property<int>("IdEstado")
                        .HasColumnName("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdEstado");

                    b.ToTable("EstadoSucursal");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            Descripcion = "Habilitada"
                        },
                        new
                        {
                            IdEstado = 2,
                            Descripcion = "Inhabilitada"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .HasColumnName("idLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("Cp")
                        .HasColumnName("CP")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnName("idProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Localidad");

                    b.HasData(
                        new
                        {
                            IdLocalidad = 1,
                            Cp = 1001,
                            IdProvincia = 1,
                            Nombre = "Retiro seccion 1"
                        },
                        new
                        {
                            IdLocalidad = 2,
                            Cp = 1002,
                            IdProvincia = 1,
                            Nombre = "Monserrat seccion 1"
                        },
                        new
                        {
                            IdLocalidad = 3,
                            Cp = 1003,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 1"
                        },
                        new
                        {
                            IdLocalidad = 4,
                            Cp = 1004,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 2"
                        },
                        new
                        {
                            IdLocalidad = 5,
                            Cp = 1005,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 3"
                        },
                        new
                        {
                            IdLocalidad = 6,
                            Cp = 1006,
                            IdProvincia = 1,
                            Nombre = "Retiro seccion 2"
                        },
                        new
                        {
                            IdLocalidad = 7,
                            Cp = 1007,
                            IdProvincia = 1,
                            Nombre = "Retiro seccion 3"
                        },
                        new
                        {
                            IdLocalidad = 8,
                            Cp = 1001,
                            IdProvincia = 1,
                            Nombre = "Monserrat seccion 2"
                        },
                        new
                        {
                            IdLocalidad = 9,
                            Cp = 1009,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 4"
                        },
                        new
                        {
                            IdLocalidad = 10,
                            Cp = 1010,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 5"
                        },
                        new
                        {
                            IdLocalidad = 11,
                            Cp = 1011,
                            IdProvincia = 1,
                            Nombre = "Retiro seccion 4"
                        },
                        new
                        {
                            IdLocalidad = 12,
                            Cp = 1012,
                            IdProvincia = 1,
                            Nombre = "Monserrat seccion 3"
                        },
                        new
                        {
                            IdLocalidad = 13,
                            Cp = 1013,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 6"
                        },
                        new
                        {
                            IdLocalidad = 14,
                            Cp = 1014,
                            IdProvincia = 1,
                            Nombre = "Recoleta seccion 1"
                        },
                        new
                        {
                            IdLocalidad = 15,
                            Cp = 1015,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion 7"
                        },
                        new
                        {
                            IdLocalidad = 16,
                            Cp = 1016,
                            IdProvincia = 1,
                            Nombre = "Recoleta seccion 2"
                        },
                        new
                        {
                            IdLocalidad = 17,
                            Cp = 1017,
                            IdProvincia = 1,
                            Nombre = "San Nicolas seccion seccion 8"
                        },
                        new
                        {
                            IdLocalidad = 18,
                            Cp = 1018,
                            IdProvincia = 1,
                            Nombre = "Recoleta seccion 3"
                        },
                        new
                        {
                            IdLocalidad = 19,
                            Cp = 1019,
                            IdProvincia = 1,
                            Nombre = "Recoleta seccion 4"
                        },
                        new
                        {
                            IdLocalidad = 20,
                            Cp = 1020,
                            IdProvincia = 1,
                            Nombre = "Recoleta seccion 5"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .HasColumnName("idProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincia");

                    b.HasData(
                        new
                        {
                            IdProvincia = 1,
                            Nombre = "Buenos Aires"
                        });
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .HasColumnName("idSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdDireccion")
                        .HasColumnName("idDireccion")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnName("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdSucursal");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstado");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Localidad", "IdLocalidadNavigation")
                        .WithMany("Direccion")
                        .HasForeignKey("IdLocalidad")
                        .HasConstraintName("FK_Direccion_Localidad")
                        .IsRequired();
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Localidad", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Provincia", "IdProvinciaNavigation")
                        .WithMany("Localidad")
                        .HasForeignKey("IdProvincia")
                        .HasConstraintName("FK_Localidad_Provincia")
                        .IsRequired();
                });

            modelBuilder.Entity("PS.Template.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("PS.Template.Domain.Entities.Direccion", "IdDireccionNavigation")
                        .WithMany("Sucursal")
                        .HasForeignKey("IdDireccion")
                        .HasConstraintName("FK_Sucursal_Direccion")
                        .IsRequired();

                    b.HasOne("PS.Template.Domain.Entities.EstadoSucursal", "IdEstadoNavigation")
                        .WithMany("Sucursal")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("FK_Sucursal_EstadoSucursal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
